import type { BlogBlock } from "./blogs";

// Full article bodies (migrated from faslebbie.com). Rendered below the hero in
// the scrollable blog modal. Kept separate from lib/blogs.ts to keep that file
// readable. Keyed by post slug. Sanity's `body` field overrides these.
export const blogBodies: Record<string, BlogBlock[]> = {
  "design-pulse-org-design-health-monitor": [
    { kind: "p", text: "Design leadership often falls into the trap of confusing activity with real impact. You might see teams that look functional on the surface but struggle to align with evolving organizational demands. This issue hit home as a design manager at Meta, where quick shifts in priorities led to constant context switching and noticeable burnout among the team." },
    { kind: "p", text: "I created the Design Pulse framework to regularly assess how design capabilities align with the organization's current needs. This became a key tool for guiding leadership decisions, from building skills to allocating resources and spotting deeper issues." },
    { kind: "p", text: "Zooming out a bit, it reshapes how teams respond to change, turning diagnosis into a practice that sustains long-term organizational health." },
    { kind: "h2", text: "How it Works" },
    { kind: "p", text: "The Design Pulse relies on a straightforward, real-time assessment across three categories. This setup helps you see where your team's energy is going and where problems might be bubbling up." },
    { kind: "p", text: "“We focused” highlights areas that are getting active investment, such as time and resources poured into building new strengths. Think of this as the growth zone, where you're pushing boundaries." },
    { kind: "p", text: "“We continued” covers the steady stuff, capabilities kept at their current level to avoid slipping backward. These are reliable practices that work fine for now, freeing up space for other priorities." },
    { kind: "p", text: "“We identified” points out the trouble spots, such as misalignments or resource drains that aren't paying off. Here, you uncover gaps that could widen if ignored, prompting necessary adjustments." },
    { kind: "h2", text: "Apply these categories across five layers: Personal, Team, Strategy, Product, and Company." },
    { kind: "p", text: "I'll break them down with examples, drawing from my experience in leading design teams." },
    { kind: "img", text: "/blog/design-pulse-org-design-health-monitor/fig-1.png" },
    { kind: "h3", text: "Personal Level: Leadership Development Health" },
    { kind: "p", text: "At this layer, you assess how individual growth supports broader capacity. “We focused” might involve targeted leadership training to tackle new challenges, or building cross-team relationships that boost design's reach. “We continued” could mean sticking with routine one-on-ones and feedback loops that keep progress steady. “We identified” often reveals skills being honed that no longer align with the org's direction, or generic development that doesn't create real impact." },
    { kind: "h3", text: "Team Level: Team Infrastructure Health" },
    { kind: "p", text: "Here, check if your team acts as a cohesive unit rather than just individuals. For “we focused,” consider strategic hires to fill knowledge gaps or initiatives that clarify career paths while meeting org needs. “We continued” includes norms that support day-to-day functioning without major tweaks. In “we identified,” you might spot behaviors drifting from org priorities, growing skill gaps, or cultures favoring personal wins over collective value, perhaps leading to bandwidth strains." },
    { kind: "h3", text: "Product Level: Design Operations Effectiveness" },
    { kind: "p", text: "Focus on how ops enable product wins and prove design's business value. “We focused” could mean evolving quality systems or encouraging experiments with new collaboration models, such as closer ties with engineering to accelerate delivery. “We continued” covers rhythms that handle the current scale adequately. “We identified” might suggest over-reliance on outdated processes, isolated ops, or imbalanced ratios that prevent designers from shipping due to engineering shortages." },
    { kind: "h3", text: "Strategy Level: Vision-Reality Alignment" },
    { kind: "p", text: "This layer examines whether strategies create real value internally and externally. In “we focused,” aim for visions that drive decisions or change efforts that get implemented. “We continued” maintains basic strategic visibility. “We identified” often refers to isolated planning or visions too detached from execution, which consume energy without producing results." },
    { kind: "h3", text: "Company Level: Organizational Design Alignment" },
    { kind: "p", text: "Assess design's fit with business strategy and politics. “We focused” involves active alignment, like joining business planning or measuring impact on key metrics. “We continued” keeps the dialogue ongoing to stay in sync. “We identified” could highlight independence from strategy, unclear value to leaders, or stagnant positioning amid business shifts." },
    { kind: "h2", text: "How to Integrate Design Pulse into Your Team's Workflow" },
    { kind: "p", text: "To make this more than a checklist, weave it into your routines as an intervention tool. Here's how I do it at Meta, with adaptations you can try." },
    { kind: "img", text: "/blog/design-pulse-org-design-health-monitor/fig-2.png" },
    { kind: "h3", text: "Weekly Pulse Cycles" },
    { kind: "p", text: "Each week, map capabilities across the layers into the categories. This creates an ongoing record of health, showing not just status, but also if your focus aligns strategically. It helped me spot imbalances early." },
    { kind: "h3", text: "Quarterly Pulse Analysis" },
    { kind: "p", text: "Every three months, review patterns over time. Ask: Have long-focused areas outlived their usefulness? Are continued items turning into routines that sap energy? Do persistently identified issues signal deeper structural problems needing broader fixes?" },
    { kind: "h3", text: "Priority Shifting Response" },
    { kind: "p", text: "Use insights to act, prioritizing key challenges while accepting some trade-offs. This shifts from reactive fixes to thoughtful systemic changes." },
    { kind: "h3", text: "What I Learned From Implementation at Meta" },
    { kind: "p", text: "Right away, it showed that 20% of our effort went to non-strategic maintenance. I emphasized that “identified” items weren't personal failings but team-wide disconnects. It also highlighted the worth of routine tasks. During layoffs, with fewer people and shifting goals, Design Pulse guided us to drop non-essentials. We moved from “do everything with less” to accepting certain gaps, revealing what was truly busywork." },
    { kind: "h2", text: "What Matters" },
    { kind: "p", text: "Ultimately, Design Pulse succeeds by linking capabilities to current needs. As leaders, you balance this with team growth." },
    { kind: "p", text: "It needs buy-in and flexibility, but offers a way to lead responsively. This practice not only navigates change but also influences how organizations evolve their design behaviors for the future." },
    { kind: "h2", text: "References" },
    { kind: "li", text: "Nielsen Norman Group — UX Maturity Models and Organizational UX" },
    { kind: "li", text: "Cameron Tonkinwise — Designing for Transitions" },
    { kind: "li", text: "Ezio Manzini — Design, When Everybody Designs" },
    { kind: "li", text: "IDEO — Designing Organizations for Change" },
    { kind: "li", text: "Gartner — Design Leadership and Organizational Change" },
    { kind: "li", text: "Accenture — The Business Value of Design" },
  ],

  "tetrahedral-model": [
    { kind: "h3", text: "A Systems Model for Cross-Disciplinary Coordination" },
    { kind: "p", text: "I've been reflecting on how the key to strong product organizations often lies beyond just assembling talented people. It's about the quality of interactions- how people connect and interact within the work environment. Often, as leaders, we pour energy into building strong teams in Product, Engineering, Design, and Research, and that makes perfect sense, since skills drive results. But even with sharp individuals, you might not get a cohesive group. The connections between departments, those unpredictable exchanges, appear to hold the true potential, though they can feel chaotic at times." },
    { kind: "p", text: "Let me share what I call the Tetrahedral Product Organization (TPO) model. This framework draws lightly from systems thinking, where stable setups rely on linked parts that adapt together. The focus isn't so much on the four main elements, but on the six links between them." },
    { kind: "p", text: "These ties handle information sharing, teamwork, and problem-solving, which can either strengthen or undermine the whole." },
    { kind: "p", text: "As a leader, you could use this view to shift from rigid silos toward a setup that anticipates tensions, fosters common goals, and builds ties that drive real product advances. Zooming out, this approach might reshape team behaviors at scale, influencing how organizations transition toward more adaptive futures." },
    { kind: "h2", text: "Where Does This Come From?" },
    { kind: "p", text: "The tetrahedral shape from systems thinking offers a simple way to map key ties in groups. Think of Buckminster Fuller's idea: it's the basic 3D form that stays solid and defines clear boundaries. Instead of viewing departments as separate, this lens highlights their coordination." },
    { kind: "p", text: "Fuller noted that stable systems need at least four points to separate inside from outside, creating conditions for internal strength and external response. In practice, this breaks down into:" },
    { kind: "p", text: "Nodes: These are steady parts that evolve slowly, like core roles in product work, each with its own ways, measures, and cultures." },
    { kind: "p", text: "Synergies: The active links between nodes, which shift quickly based on how people communicate and work together. You can adjust these through daily changes, unlike the nodes themselves." },
    { kind: "p", text: "Fields: Areas that pop up when three nodes connect, sparking fresh ideas that no single group could create alone." },
    { kind: "p", text: "The Void: This is the built-up wisdom and gut-level choices that come when everything else clicks." },
    { kind: "p", text: "This setup reminds me of models like the Tetrahedral Model of Performance, where personal, group, and company levels meet cultural bases." },
    { kind: "img", text: "/blog/tetrahedral-model/fig-1.png" },
    { kind: "h2", text: "The Six Synergies That Make or Break Teams" },
    { kind: "p", text: "In product settings, the four nodes line up as:" },
    { kind: "li", text: "Product Management: Handling strategy, needs, and market checks." },
    { kind: "li", text: "Design: Covering User experience research, interface design, and usability testing." },
    { kind: "li", text: "Engineering: Technical architecture, implementation, system performance." },
    { kind: "li", text: "Research: Digging into user behavior analysis, market validation, and evidence generation." },
    { kind: "p", text: "These form your base, changing gradually. These nodes form your stable foundation, the core competencies that change slowly and resist disruption." },
    { kind: "p", text: "But the six synergies? That's where things get interesting, or fall apart." },
    { kind: "p", text: "Product to Design: Strategy and user experience inform each other. Business goals align with user needs. When it doesn't, design becomes decorative. Strategy ignores user experience. You end up with feature factories." },
    { kind: "p", text: "Product to Engineering: Reality shapes plans. Technical feasibility shapes strategic decisions. Roadmaps reflect engineering realities. When it doesn't, engineering becomes an order-taking function. Technical debt accumulates from unrealistic timelines." },
    { kind: "p", text: "Product to Research: Strategy gets backed by evidence. Market insights drive product decisions. When it doesn't, research becomes confirmation bias. Data gets cherry-picked to support predetermined strategies." },
    { kind: "p", text: "Design to Engineering: Technical constraints inspire creative solutions. Implementation enhances design intent. When it doesn't, you get “Design vs. Engineering” battles. Solutions that look good but perform poorly, or engineering solutions users don't use." },
    { kind: "p", text: "Design to Research: User insights directly inform design decisions. Design solutions get validated with real users. When it doesn't, research becomes a post-hoc justification. Design based on assumptions rather than evidence." },
    { kind: "p", text: "Engineering to Research: Technical decisions are informed by user behavior data. Performance optimization driven by usage patterns. When it doesn't, engineering optimization happens in isolation. Technical metrics disconnected from user impact." },
    { kind: "h2", text: "When Things Go Wrong" },
    { kind: "p", text: "What concerns me is how often bad links go unnoticed. Teams might seem okay, with meetings and outputs flowing, yet underlying issues erode trust over time. I've noticed signs like one-way info flows, say, Research feeds Product but skips Engineering. Or blame-filled talk, like “They can't build it” instead of joint exploration. Groups tackle similar issues alone, metrics clash without links, disputes settle by rank, not facts." },
    { kind: "p", text: "These can lead to a strategy without user input, creating usable but aimless features. Or designs that please but miss goals. Tech choices ignore behavior, optimizations drift from impact. Quality comes from push-pull, not team-ups. It's not always clear-cut; sometimes a strong link in one area masks weaknesses elsewhere, but addressing them early prevents bigger rifts." },
    { kind: "h2", text: "Building Better Connections" },
    { kind: "p", text: "Fixing bad “links” doesn't mean redrawing your structure. Focus on practices that boost links." },
    { kind: "p", text: "Design Information Flow: Chart how knowledge moves. Does research reach all? How do tech hurdles hit Product? Strong setups act like smart info hubs." },
    { kind: "p", text: "Share Metrics: Tie success across groups. The product might track user joy from Design and Research. Engineering could watch use-based speeds." },
    { kind: "p", text: "Set Rituals: Beyond weeklies, try pair-ups, reviews, and deep dives needing multiple inputs." },
    { kind: "p", text: "Rotate Views: Embed folks briefly. Product shadows research, Engineers join critiques, Designers see data." },
    { kind: "p", text: "Spot Issues: Use retros on ties; provide feedback on blocks." },
    { kind: "img", text: "/blog/tetrahedral-model/fig-2.png" },
    { kind: "h2", text: "The Fields: Where New Things Emerge" },
    { kind: "p", text: "Get synergies right, and fresh zones appear from three-way ties. Product, design, and engineering might uncover technical fixes for user pain points. Design, research, and engineering spots build chances that research alone misses. Product research and engineering identify markets that need new tech." },
    { kind: "p", text: "These areas hold your edge, the spots where linked work breeds novelty. Though not every triangle yields gold right away, nurturing them builds resilience." },
    { kind: "h2", text: "A Practical Starting Point: The Synergy Audit" },
    { kind: "p", text: "To try this, start simple with an audit:" },
    { kind: "p", text: "Map flows: Track current information flows and their movement between nodes. How does information currently move between Product, Design, Engineering, and Research?" },
    { kind: "p", text: "Spot negative patterns: Look for blame, clashes, and misfits. Where do you see defensive language, escalated conflicts, or misaligned metrics?" },
    { kind: "p", text: "Plan fixes: Pick practices for weak spots. Design positive interventions. What specific practices could improve the weakest links?" },
    { kind: "p", text: "Check progress: Measure if changes help. Create feedback loops. How will you know if your interventions are working?" },
    { kind: "p", text: "Build on wins: Iterate and strengthen. Grow strong links, watch weak ones. Which positive links can you amplify? Which negative ones need continued attention?" },
    { kind: "img", text: "/blog/tetrahedral-model/fig-3.png" },
    { kind: "h2", text: "Beyond Process: The Mindset Shift" },
    { kind: "p", text: "I've found that the real power of this tetrahedral model lies in how it reframes what we prioritize as leaders. It's not just about refining processes or adding more meetings; it's about cultivating a mindset that values the spaces between disciplines as much as the disciplines themselves. You start by recognizing that exceptional product work emerges from these interconnections, where tensions become opportunities for shared understanding rather than roadblocks." },
    { kind: "p", text: "This shift means moving away from optimizing individual roles in isolation, toward designing conditions that let Product, Design, Engineering, and Research thrive together." },
    { kind: "p", text: "In my experience, that often involves acknowledging trade-offs, such as short-term efficiency for long-term resilience in team behavior. Zooming out, this isn't merely operational; it participates in transitioning your organization toward futures where adaptability is baked into the culture rather than bolted on." },
    { kind: "p", text: "To make it stick, examine your own patterns first. How do you, as a leader, model these synergies in your daily decisions? Start small: Track a week's worth of cross-team interactions in your group. Note where collaboration flows naturally and where isolation creeps in. Those observations will reveal practical entry points, without overwhelming your team. The goal isn't perfection, but steady progress toward a system where connections drive not just better products, but healthier, more sustainable ways of working. With patience, you'll see how these subtle changes build momentum, creating an organization that's equipped for whatever comes next." },
    { kind: "h2", text: "References" },
    { kind: "li", text: "Buckminster Fuller — Synergetics" },
    { kind: "li", text: "Donella Meadows — Thinking in Systems" },
    { kind: "li", text: "Cameron Tonkinwise — Designing for Transitions" },
    { kind: "li", text: "IDEO — Designing Organizations for Collaboration" },
    { kind: "li", text: "Harvard Business Review — The New Science of Building Great Teams" },
    { kind: "li", text: "Nielsen Norman Group — Cross-Functional Collaboration in Product Teams" },
  ],

  "design-handbook-that-works": [
    { kind: "h3", text: "Why your brilliant ideas from your last company might be sabotaging your new team and what I've learned about doing it differently." },
    { kind: "p", text: "You know that urge to pull out your old playbook when you step into a new design leadership role? I've felt it too: ignoring failed strategies, carrying proven approaches from past companies, only to watch them fall flat. It turns out those solutions, solid as they seemed before, often clash with the new environment. They can even push your team away if you force them on your team." },
    { kind: "p", text: "Over several roles, I've shifted my thinking, focusing instead on understanding what the current workplace environment stimulates or represses before building anything." },
    { kind: "p", text: "This helps create strategies that stick because they're born from the team's reality, not just my past wins." },
    { kind: "img", text: "/blog/design-handbook-that-works/fig-1.png" },
    { kind: "h2", text: "Ditch Your Solutions (For Now) and Learn the Landscape" },
    { kind: "p", text: "Start by setting aside what worked elsewhere. Environments can either support design efforts or quietly undermine them, much like how certain conditions nourish basic human needs while others block them. In organizations, this might mean spotting patterns that help or hinder team behaviors right away." },
    { kind: "p", text: "When starting a new role, I suggest kicking off with a focused workshop, bringing in your design team and folks from engineering or product, if you can. The aim is to map out how design really functions here, what boosts it, and what drags it down. Sure, some places balk at the time commitment, but I've found this early step saves headaches later, avoiding months of misfires. In a pinch, like at a startup in crisis mode, shorten it to a few hours spread out over time. Even that bit of diagnosis builds a stronger base than jumping straight to solutions." },
    { kind: "img", text: "/blog/design-handbook-that-works/fig-2.png" },
    { kind: "h3", text: "Day One: Where Are We?" },
    { kind: "p", text: "Don't dive into big visions yet. Begin with the everyday hurdles. When I led the EIS Design team at Meta, we mapped trust flows and pushback between groups, asking things like: How does engineering usually react to design ideas? Where do real product calls happen? What sank the last design push, and why? Who holds informal sway? These questions often uncover raw truths about the org. It can feel a bit uncomfortable, but it's key to seeing the landscape clearly." },
    { kind: "h3", text: "Day Two: How Did We End Up Here?" },
    { kind: "p", text: "Next, trace back how things got this way. Past choices can lock in paths that make some changes easy and others tough, shaping future behaviors in subtle ways. We dig into decision histories, failed tries from before, and outside pressures like market shifts." },
    { kind: "p", text: "This helps explain stuck conversations or tense ties. It's not always easy, but I've seen it give teams the context they need to move forward without repeating old mistakes." },
    { kind: "h3", text: "Day Three: Where Do We Want To Go?" },
    { kind: "p", text: "By this point, something shifts. Teams start spotting their own needs, rather than waiting for you to dictate. Wrap with a shared map of the now, the past, and the hoped-for future. Set commitments across short, mid, and long terms: quick wins in 30 days, solid shifts in a year, deeper changes over three." },
    { kind: "p", text: "At Meta, this birthed our first EISA Design & Research handbook, tailored to our setup, with strategy, goals, and measures co-created across teams. It had real buy-in because it grew from that group work." },
    { kind: "img", text: "/blog/design-handbook-that-works/fig-3.png" },
    { kind: "h2", text: "Making Design Part of the Engineering Solution" },
    { kind: "p", text: "Design Handbooks flop when they're designer-only affairs shoved down others' throats. Try a collaborative tack instead. At Meta's engineering-heavy culture, we led with that on page one, positioning design as a front-end boost to engineering. Not perfect, maybe, but it fit and worked. Seek allies in product and engineering early; you need at least one per group who sees design's wins as theirs too. If they're missing, that signals you might build basics first, like ties, before processes." },
    { kind: "p", text: "Your Design & Research Handbook should hold agreed roles in the bigger system:" },
    { kind: "li", text: "Success markers that click for everyone, not just design." },
    { kind: "li", text: "Processes respecting real limits, like deadlines." },
    { kind: "li", text: "Communication that matches how others operate." },
    { kind: "li", text: "Ways to update it as things change." },
    { kind: "p", text: "Proven methods travel, but how you apply them varies. User research helps anywhere, yet its form, from formal ops to quick embeds, depends on the spot." },
    { kind: "h2", text: "Test the Waters First" },
    { kind: "p", text: "Before going big, gauge maturity. In a hierarchy where design serves others, focus your handbook on tactics: delivering credible work, backing choices, growing influence bit by bit." },
    { kind: "p", text: "Probe with sharp questions: Does leadership buy the value? Can partners handle new ways of working, or are they swamped? What pressures, like cuts or reorgs, might derail? Do you have the clout?. Keep it alive and avoid bureaucratic traps in implementing new strategic ideas." },
    { kind: "p", text: "I've seen others morph into burdens that consume time without real returns. To prevent that, link reviews to business cycles, designate owners for sections, log divergences between docs and practice, and measure with clear, shared metrics. Zooming out, this keeps the handbook as a living tool that adapts organizational behaviors, not a static artifact." },
    { kind: "p", text: "I focus on cultivating conditions where design flourishes naturally, then document what emerges. If a full strategic handbook risks bureaucracy, opt for lighter alternatives, such as shared wikis or quick-start guides. In environments that suppress collaboration, even solid docs gather dust." },
    { kind: "p", text: "This diagnostic mindset has sharpened my leadership, ensuring ideas take root in context." },
    { kind: "p", text: "No matter if you're entering a mature org or bootstrapping design, it clarifies precisely what to capture and whether a handbook serves the team's future at all." },
    { kind: "h2", text: "References" },
    { kind: "li", text: "Ezio Manzini — Design, When Everybody Designs" },
    { kind: "li", text: "Cameron Tonkinwise — Designing for Transitions" },
    { kind: "li", text: "IDEO — Designing Organizations for Change" },
    { kind: "li", text: "Nielsen Norman Group — UX Maturity Models" },
    { kind: "li", text: "Harvard Business Review — Why Change Programs Don't Produce Change" },
    { kind: "li", text: "Don Norman — The Design of Everyday Things" },
  ],

  "trust-through-five-expectations": [
    { kind: "h3", text: "How to build trust and clarity with your team across all levels of design work" },
    { kind: "p", text: "After eight years leading design teams, I've learned good intentions only get you so far. Hiring sharp people, handing them interesting problems, and mostly staying out of their way was enough. Some designers bloom in that space. Most quietly drift, feeling their work exists in a vacuum, disconnected from strategy, impact, or even recognition." },
    { kind: "p", text: "Over time, I've distilled this into five explicit expectations I now share on day one with every designer I lead. They're less about rules and more about creating the conditions for shared understanding, so we can do our best work together while connecting individual efforts to larger goals." },
    { kind: "h2", text: "Know How You Work Best (and Tell Me)" },
    { kind: "h3", text: "Start with the person, not the process." },
    { kind: "p", text: "I hand new team members a simple Working Style sheet: nothing fancy, just questions about when you think deepest, how you like feedback, what drains you, and what lights you up. One designer told me weekly syncs were killing her momentum; she needed long, uninterrupted mornings. We shifted her cadence, and six weeks later, she was shipping the strongest work of her career. When you're honest about your superpowers and blind spots, I can build balanced pairs and squads where everyone actually learns from each other." },
    { kind: "p", text: "This single practice has saved more careers than any performance review I've ever run." },
    { kind: "img", text: "/blog/trust-through-five-expectations/fig-1.png" },
    { kind: "h2", text: "Own the Full Wake of Your Decisions" },
    { kind: "h3", text: "Your work keeps living in the world long after you ship it. Stay awake to what it's doing." },
    { kind: "p", text: "Notice when a pattern quietly shifts power, creates friction for certain users, or locks in a behavior we'll regret later. Bring it forward. Those observations are where real strategic thinking begins. I've watched mid-level designers spot second-order effects that completely changed roadmap priorities. That only happens when people feel safe saying, “This thing we built is starting to feel off.” Zooming out, this isn't just about accountability; it reshapes the behaviors that sustain ethical design practices over time." },
    { kind: "img", text: "/blog/trust-through-five-expectations/fig-2.png" },
    { kind: "h2", text: "Protect Deep Work While Staying in the Conversation" },
    { kind: "h3", text: "Great design needs both solitude and collision. Guard the first, show up fully for the second." },
    { kind: "p", text: "Block real thinking time without guilt: turn off Slack, close the door, whatever it takes. Breakthroughs rarely survive constant pinging. At the same time, when it's time for crit, sync, or helping a teammate unblock, be there, prepared, and generous." },
    { kind: "p", text: "The teams that last find this balance instinctively." },
    { kind: "p", text: "They treat deep work as non-negotiable and collective intelligence as sacred. The rhythm feels almost biological: inhale alone, exhale together." },
    { kind: "img", text: "/blog/trust-through-five-expectations/fig-3.png" },
    { kind: "h2", text: "Always Know How Your Work Moves the Company" },
    { kind: "h3", text: "Never let your designs be the best-kept secret in the building." },
    { kind: "p", text: "Once a month, surface one clear example, like adoption lift, support deflection, or revenue impact, and turn it into a short story you can tell upward or sideways. I've seen a single slide from a senior designer swing an entire quarterly plan." },
    { kind: "p", text: "This habit gives leadership undeniable proof of design's leverage and keeps you from waking up one day to realize you've been decorating someone else's strategy." },
    { kind: "img", text: "/blog/trust-through-five-expectations/fig-4.png" },
    { kind: "h2", text: "Build Real Relationships Across the Org" },
    { kind: "h3", text: "Design is always a collaboration within complicated systems." },
    { kind: "p", text: "Schedule recurring coffee or 20-minute syncs with your key product, eng, research, and marketing partners. Learn with genuine curiosity what keeps them up at night. Show early work, ask dumb questions, give them context before they need it. Over time, those relationships become the hidden rails that let good design actually ship." },
    { kind: "p", text: "I've watched designers who used to complain about being treated like a service flip the script entirely once they invested in these human bridges. Suddenly, stakeholders were fighting for their ideas." },
    { kind: "img", text: "/blog/trust-through-five-expectations/fig-5.png" },
    { kind: "h3", text: "Laying Foundations for Great Design Work" },
    { kind: "p", text: "These five expectations only work when the company already values creativity at least a little. In my experience mentoring teams, holding them loosely as a foundation quietly rewires the daily practices that keep a team healthy, strategic, and resilient for years." },
    { kind: "p", text: "Start with whichever feels most missing right now. Tweak, abandon, or reinvent anything that doesn't fit your context. The point isn't compliance; it's shared clarity about how we work together to do work that lasts. As a leader, you may need to adapt these ideas, providing tools while respecting different approaches, to ensure processes serve creativity rather than constrain it." },
    { kind: "h2", text: "References" },
    { kind: "li", text: "Teresa Amabile & Steven Kramer — The Progress Principle" },
    { kind: "li", text: "Don Norman — Design, Design Thinking, and Ethical Responsibility" },
    { kind: "li", text: "Nielsen Norman Group — Psychological Safety and UX Team Performance" },
    { kind: "li", text: "Cal Newport — Deep Work" },
    { kind: "li", text: "IDEO — Designing Collaboration and Trust Across Teams" },
    { kind: "li", text: "Cameron Tonkinwise — Designing for Transitions" },
  ],

  "commitments-to-a-design-team": [
    { kind: "h3", text: "How systematic leadership across five organizational levels creates conditions for teams to thrive, from individual wellbeing to company-wide influence." },
    { kind: "p", text: "You might think leadership means having all the answers, but in my experience, it's more about shaping the relationships and conditions that let others shine in their work. Over years leading design teams, I've found that strong leadership often comes down to setting clear commitments and sticking to them. These aren't just words; they appear to guide daily actions that influence how teams operate. Let me share five that have worked for me, blending practical steps with a touch of systems thinking." },
    { kind: "img", text: "/blog/commitments-to-a-design-team/fig-1.png" },
    { kind: "img", text: "/blog/commitments-to-a-design-team/fig-2.png" },
    { kind: "h2", text: "Personal: Prioritizing Team Members' Wellbeing and Growth" },
    { kind: "p", text: "Start by checking in weekly with each team member through one-on-ones. I use these to cover project updates, tackle roadblocks, discuss career paths, and build real connections. It's key to leave room for whatever's weighing on them, and I make sure I'm available beyond scheduled times too." },
    { kind: "p", text: "Team health sets the foundation for everything else." },
    { kind: "p", text: "You should watch for signs of stress or overload, encouraging honest talks about workload to avoid burnout. When people feel hesitant to voice issues, their creativity suffers. I model this by admitting when I'm unsure or learning right there with the team, much like how Figma's approach suggests fostering psychological safety for better ideas." },
    { kind: "p", text: "I also focus on resources and opportunities that build belonging. Diverse views often lead to stronger designs, though it takes effort to create fair conditions for everyone." },
    { kind: "h2", text: "Product: Elevating Design Craft" },
    { kind: "p", text: "Give designers real ownership over their work's quality, as it ties directly to accountability for outcomes. I group teams around products based on their skills, background, and goals, keeping these groups intact even after projects end. Breaking them up too soon can waste the shared knowledge they've built, and maintaining that continuity feels like a smart way to design ongoing collaboration." },
    { kind: "p", text: "Trust them with clear metrics for success, offering tools while honoring their unique styles. I work to link design quality to business results, considering impacts on users, teams, and even broader stakeholders who might not be obvious at first." },
    { kind: "p", text: "Above all, push for trimming scope instead of skimping on quality. A focused, polished release usually beats a rushed, sprawling one, in my view." },
    { kind: "h2", text: "Team: Building Intimate, Autonomous, and Continuously Learning Teams" },
    { kind: "p", text: "Teams don't gel through quick exercises alone. I kick things off with workshops drawing from group formation ideas, like those from Schutz, to foster genuine bonds. This isn't about forced fun; it's about creating the social setup for effective work together." },
    { kind: "p", text: "Use process sparingly, trusting folks to decide and flag problems. Too many rules can stifle ideas, turning things mechanical. Coach them to sharpen their own judgment on work, so they lead more on their own." },
    { kind: "p", text: "Carve out time for trying new things, learning from the field, and honing skills. Set up channels for input that suit different styles, syncing up in real time or async." },
    { kind: "p", text: "In our weekly syncs, we zero in on results over just showing off. Keep feedback personal and private, as public critiques can erode trust fast. I seek monthly input on my leading style too, keeping accountability two-way." },
    { kind: "h2", text: "Strategy: Design as a Driver of Future Vision" },
    { kind: "p", text: "Strategy thrives on shared input. Those carrying it out need to believe in it, not just follow orders. I set up solid research systems to guide choices and check designs, treating it as core to thinking ahead rather than an add-on." },
    { kind: "p", text: "Run workshops where everyone helps shape what excellent design looks like for us. This recognizes strategy as a group design challenge, pulling in varied angles. Empower your team to influence roadmaps with user data, showing design's worth through solid evidence and tracked results." },
    { kind: "p", text: "Hold regular sessions for feedback from the team and partners in product or engineering. We review goals and adjust, folding insights into how I lead and our plans." },
    { kind: "h2", text: "Organization: Building Design's Influence" },
    { kind: "p", text: "Design's strength grows from ties with engineering and product. As it succeeds, that effect spreads. I see design as woven into their efforts, defining the full experience." },
    { kind: "p", text: "Build those links by showing how design fits their goals. Share the why behind ideas, not just finals, via open talks and joint sessions. Craft processes where teams co-create visions, earning commitment through involvement." },
    { kind: "p", text: "Grow the team thoughtfully, targeting specific skill needs. Each new hire should fill a gap with a plan for quick contributions, avoiding growth just for growth's sake." },
    { kind: "h2", text: "The Way Forward" },
    { kind: "p", text: "These commitments across Personal, Product, Team, Strategy, and Organization form the everyday habits that have shaped my teams. They link personal growth to group wins and keep design central in the business. But remember, commitments only matter if you follow through, especially under pressure." },
    { kind: "p", text: "When things get tough, deadlines press, or tensions rise, that's when they count most, though it's tempting to let them slide. How we structure work is design in action, with lasting effects on the behaviors and futures we enable in our organizations." },
    { kind: "img", text: "/blog/commitments-to-a-design-team/fig-3.png" },
    { kind: "h2", text: "References" },
    { kind: "li", text: "Figma — Building Resilient Design Teams" },
    { kind: "li", text: "Don Norman — The Design of Everyday Things" },
    { kind: "li", text: "William Schutz — FIRO: A Three-Dimensional Theory of Interpersonal Behavior" },
    { kind: "li", text: "IDEO — Designing Teams and Cultures for Creativity" },
    { kind: "li", text: "Nielsen Norman Group — Psychological Safety and UX Team Performance" },
    { kind: "li", text: "Cameron Tonkinwise — Designing for Transitions" },
  ],
};
